An academic task

# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo = pd.read_csv(url, delimiter="\t")
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [12]:
chipo[chipo["item_price"]>"$10.00"]

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99
...,...,...,...,...,...
4586,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
4587,1824,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.25
4588,1824,1,Chips and Guacamole,NaN,$4.45
4589,1825,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.25
4590,1825,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25
4591,1825,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$8.75
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,1826,1,Chips and Guacamole,NaN,$4.45
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,1827,1,Chips and Guacamole,NaN,$4.45
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,1828,1,Chips and Guacamole,NaN,$4.45
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [5]:
chipo_two_cols =chipo[["item_name","item_price"]]
chipo_two_cols.head()

                               item_name item_price
0           Chips and Fresh Tomato Salsa     $2.39
1                                   Izze     $3.39
2                       Nantucket Nectar     $3.39
3  Chips and Tomatillo-Green Chili Salsa     $2.39
4                           Chicken Bowl    $16.98

### Step 6. Sort by the name of the item

In [6]:
chipo_two_cols.sort_values("item_name")

              item_name item_price
3389  6 Pack Soft Drink    $12.98
341   6 Pack Soft Drink     $6.49
1849  6 Pack Soft Drink     $6.49
1860  6 Pack Soft Drink     $6.49
2713  6 Pack Soft Drink     $6.49
3422  6 Pack Soft Drink     $6.49
553   6 Pack Soft Drink     $6.49
1916  6 Pack Soft Drink     $6.49
1922  6 Pack Soft Drink     $6.49
1937  6 Pack Soft Drink     $6.49
3836  6 Pack Soft Drink     $6.49
298   6 Pack Soft Drink     $6.49
1976  6 Pack Soft Drink     $6.49
1167  6 Pack Soft Drink     $6.49
3875  6 Pack Soft Drink     $6.49
1124  6 Pack Soft Drink     $6.49
3886  6 Pack Soft Drink     $6.49
2108  6 Pack Soft Drink     $6.49
3010  6 Pack Soft Drink     $6.49
4535  6 Pack Soft Drink     $6.49
4169  6 Pack Soft Drink     $6.49
4174  6 Pack Soft Drink     $6.49
4527  6 Pack Soft Drink     $6.49
4522  6 Pack Soft Drink     $6.49
3806  6 Pack Soft Drink     $6.49
2389  6 Pack Soft Drink     $6.49
3132  6 Pack Soft Drink     $6.49
3141  6 Pack Soft Drink     $6.49
639   6 Pack Soft Drink     $6.49
1026  6 Pack Soft Drink     $6.49
...                 ...        ...
2996       Veggie Salad     $8.49
3163       Veggie Salad     $8.49
4084       Veggie Salad     $8.49
1694       Veggie Salad     $8.49
2756       Veggie Salad     $8.49
4201  Veggie Salad Bowl    $11.25
1884  Veggie Salad Bowl    $11.25
455   Veggie Salad Bowl    $11.25
3223  Veggie Salad Bowl    $11.25
2223  Veggie Salad Bowl     $8.75
2269  Veggie Salad Bowl     $8.75
4541  Veggie Salad Bowl     $8.75
3293  Veggie Salad Bowl     $8.75
186   Veggie Salad Bowl    $11.25
960   Veggie Salad Bowl     $8.75
1316  Veggie Salad Bowl     $8.75
2156  Veggie Salad Bowl    $11.25
4261  Veggie Salad Bowl    $11.25
295   Veggie Salad Bowl    $11.25
4573  Veggie Salad Bowl     $8.75
2683  Veggie Salad Bowl     $8.75
496   Veggie Salad Bowl    $11.25
4109  Veggie Salad Bowl    $11.25
738   Veggie Soft Tacos    $11.25
3889  Veggie Soft Tacos    $16.98
2384  Veggie Soft Tacos     $8.75
781   Veggie Soft Tacos     $8.75
2851  Veggie Soft Tacos     $8.49
1699  Veggie Soft Tacos    $11.25
1395  Veggie Soft Tacos     $8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [7]:
chipo[["quantity","item_price","item_name"]].sort_values("item_price", ascending=False)

      quantity item_price              item_name
2624         1     $9.39        Steak Salad Bowl
4419         1     $9.39        Steak Salad Bowl
4036         1     $9.39        Steak Salad Bowl
1825         1     $9.39     Barbacoa Salad Bowl
3115         1     $9.39     Carnitas Salad Bowl
4547         1     $9.39        Steak Salad Bowl
3098         1     $9.39        Steak Salad Bowl
4241         1     $9.39        Steak Salad Bowl
1418         1     $9.39     Barbacoa Salad Bowl
4391         1     $9.39        Steak Salad Bowl
4572         1     $9.39        Steak Salad Bowl
2600         1     $9.39        Steak Salad Bowl
607          1     $9.39        Steak Salad Bowl
4390         1     $9.39     Barbacoa Salad Bowl
1865         1     $9.39     Carnitas Salad Bowl
1421         1     $9.39     Barbacoa Salad Bowl
3356         1     $9.39     Barbacoa Salad Bowl
1789         1     $9.25     Carnitas Soft Tacos
1771         1     $9.25           Steak Burrito
418          1     $9.25           Barbacoa Bowl
1812         1     $9.25        Barbacoa Burrito
763          1     $9.25   Barbacoa Crispy Tacos
3486         1     $9.25              Steak Bowl
3565         1     $9.25           Steak Burrito
2467         1     $9.25           Steak Burrito
3564         1     $9.25           Steak Burrito
3549         1     $9.25           Barbacoa Bowl
3535         1     $9.25           Steak Burrito
3563         1     $9.25           Steak Burrito
405          1     $9.25     Carnitas Soft Tacos
...        ...        ...                    ...
1805         1     $1.09             Canned Soda
1290         1     $1.09             Canned Soda
2410         1     $1.09           Bottled Water
3020         1     $1.09             Canned Soda
3021         1     $1.09           Bottled Water
180          1     $1.09             Canned Soda
280          1     $1.09             Canned Soda
3499         1     $1.09           Bottled Water
2443         1     $1.09             Canned Soda
3042         1     $1.09           Bottled Water
3498         1     $1.09             Canned Soda
779          1     $1.09             Canned Soda
28           1     $1.09             Canned Soda
780          1     $1.09           Bottled Water
3062         1     $1.09             Canned Soda
195          1     $1.09             Canned Soda
4051         1     $1.09             Canned Soda
34           1     $1.09           Bottled Water
807          1     $1.09             Canned Soda
958          1     $1.09             Canned Soda
200          1     $1.09             Canned Soda
3477         1     $1.09             Canned Soda
3476         1     $1.09             Canned Soda
956          1     $1.09             Canned Soda
4069         1     $1.09           Bottled Water
3145         1     $1.09             Canned Soda
414          1     $1.09             Canned Soda
3162         1     $1.09             Canned Soda
821          1     $1.09             Canned Soda
1457         1     $1.09             Canned Soda

[4622 rows x 3 columns]

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [8]:
v_g_salad = chipo[chipo["item_name"]=="Veggie Salad Bowl"]
v_g_salad["item_name"].count()

18

### Step 9. How many times people orderd more than one Canned Soda?

In [9]:
chipo_soda_count = chipo[chipo["item_name"]=="Canned Soda"]
chipo_soda_count.count()

order_id              104
quantity              104
item_name             104
choice_description    104
item_price            104
dtype: int64

In [10]:
chipo[(chipo["item_name"]=="Canned Soda") & (chipo["quantity"]>1)]["quantity"].count()

20